<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="halcondotnet">
      <HintPath>$(HALCONROOT)\bin\dotnet35\halcondotnet.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
